### ISSUE TITLE
Question about Eq. 7

### ISSUE THREAD

**Issue by RuyiLian** [rickgroen/cov-weighting#1]
Hi,

Thanks for your great work. I just have a question about Eq.7 in your paper 
<img width="590" alt="image" src="https://user-images.githubusercontent.com/54995948/114427694-58f1d280-9b89-11eb-9a91-0b869ad3d0b5.png">

In your implementation (`losses/covweighting_loss.py`) you use: 
```python
self.running_S_l += (x_l - self.running_mean_l) * (x_l - new_mean_l)
running_variance_l = self.running_S_l / (self.current_iter + 1)
self.running_std_l = torch.sqrt(running_variance_l + 1e-8)
```
I don't understand how this corresponds to the original Eq. 7. Could you please explain it? Thanks!

**Comment by rickgroen** [comment]
Hi,

No problem!
Originally the Welford's algorithm estimates the variance as:
![image](https://user-images.githubusercontent.com/22703638/114580956-989ae600-9c7f-11eb-9e0b-5cddc9dc70ed.png)
But we can rewrite:
![image](https://user-images.githubusercontent.com/22703638/114581025-abadb600-9c7f-11eb-88af-037d49c4f8ee.png)

However, this adds an increasingly small value due to the factor t, which is problematic when t gets large. The code makes use of sum of squares of differences from the mean to alleviate this problem. The paper equation and the one in the code end up doing the same, but the code implementation is a more numerically stable method of computing the standard deviation.

Hope it helps!

**Comment by RuyiLian** [comment]
Thanks for your reply! It really helps a lot!

**Comment by Yiming-Xie** [comment]
@rickgroen Hi! I have read your reply above, but I think that if the code is meant to use the sum of squares of differences, the order of the code snippet should be as follows: 
```
new_mean_l = mean_param * self.running_mean_l + (1 - mean_param) * x_l
self.running_mean_l = new_mean_l
self.running_S_l += (x_l - self.running_mean_l) * (x_l - new_mean_l)
```
This is because in your current code version, the variable `self.running_mean_l` represents the mean up to the last iteration, not the current iteration. Could you please help me with this question?
